import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "src/layouts/global-theme";
import {cn} from "src/utils/tailwind";
import MainLayout from "src/layouts/main-layout";
import AppProvider from "src/providers/app-provider";
import Toast from "src/layouts/Toast";
import FullscreenLoader from "src/layouts/fullscreen-loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "dark dark:bg-zinc-950 bg-white text-white")}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            disableTransitionOnChange
            enableSystem
        >
          <AppProvider>
            <Toast>
              <FullscreenLoader>
                <MainLayout>
                  {children}
                </MainLayout>
              </FullscreenLoader>
            </Toast>
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
